// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus
{
    using Models;

    /// <summary>
    /// </summary>
    public partial interface IMailPlusClient : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        Newtonsoft.Json.JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        Newtonsoft.Json.JsonSerializerSettings DeserializationSettings { get; }


            /// <summary>
        /// Get details of a campaign mailing
        /// </summary>
        /// <remarks>
        /// Returns the details of a given mailing sent by a campaign,
        /// including details of the used links.
        /// </remarks>
        /// <param name='encryptedMailingId'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetCampaignMailingDetailsWithHttpMessagesAsync(string encryptedMailingId, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get bounces for a campaign mailing
        /// </summary>
        /// <remarks>
        /// Returns bounced contacts.
        /// </remarks>
        /// <param name='encryptedMailingId'>
        /// </param>
        /// <param name='after'>
        /// </param>
        /// <param name='pageSize'>
        /// </param>
        /// <param name='fromDate'>
        /// </param>
        /// <param name='toDate'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetCampaignMailingBouncesWithHttpMessagesAsync(string encryptedMailingId, int? after = default(int?), int? pageSize = default(int?), System.DateTime? fromDate = default(System.DateTime?), System.DateTime? toDate = default(System.DateTime?), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get clicks for a campaign mailing
        /// </summary>
        /// <remarks>
        /// Returns contacts who clicked a link in a given mailing. Link
        /// details can be retrieved by using the GET method
        /// /campaign-mailing/{encryptedMailingId}.
        /// </remarks>
        /// <param name='encryptedMailingId'>
        /// </param>
        /// <param name='after'>
        /// </param>
        /// <param name='pageSize'>
        /// </param>
        /// <param name='fromDate'>
        /// </param>
        /// <param name='toDate'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetCampaignMailingClicksWithHttpMessagesAsync(string encryptedMailingId, int? after = default(int?), int? pageSize = default(int?), System.DateTime? fromDate = default(System.DateTime?), System.DateTime? toDate = default(System.DateTime?), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get clicks for a campaign mailing for a contact
        /// </summary>
        /// <remarks>
        /// Returns click interactions for a given contact in a specified
        /// mailing. Link details can be retrieved by using the GET method
        /// /campaign-mailing/{encryptedMailingId}.
        /// </remarks>
        /// <param name='encryptedMailingId'>
        /// </param>
        /// <param name='campaignSubscriptionId'>
        /// </param>
        /// <param name='after'>
        /// </param>
        /// <param name='pageSize'>
        /// </param>
        /// <param name='fromDate'>
        /// </param>
        /// <param name='toDate'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetCampaignMailingContactClicksWithHttpMessagesAsync(string encryptedMailingId, int campaignSubscriptionId, int? after = default(int?), int? pageSize = default(int?), System.DateTime? fromDate = default(System.DateTime?), System.DateTime? toDate = default(System.DateTime?), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get opens for a campaign mailing
        /// </summary>
        /// <remarks>
        /// Returns contacts who opened a given mailing.
        /// </remarks>
        /// <param name='encryptedMailingId'>
        /// </param>
        /// <param name='after'>
        /// </param>
        /// <param name='pageSize'>
        /// </param>
        /// <param name='fromDate'>
        /// </param>
        /// <param name='toDate'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetCampaignMailingOpensWithHttpMessagesAsync(string encryptedMailingId, int? after = default(int?), int? pageSize = default(int?), System.DateTime? fromDate = default(System.DateTime?), System.DateTime? toDate = default(System.DateTime?), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get opens for a campaign mailing for a contact
        /// </summary>
        /// <remarks>
        /// Returns open interations for a given contact in a specified
        /// mailing.
        /// </remarks>
        /// <param name='encryptedMailingId'>
        /// </param>
        /// <param name='campaignSubscriptionId'>
        /// </param>
        /// <param name='after'>
        /// </param>
        /// <param name='pageSize'>
        /// </param>
        /// <param name='fromDate'>
        /// </param>
        /// <param name='toDate'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetCampaignMailingContactOpensWithHttpMessagesAsync(string encryptedMailingId, int campaignSubscriptionId, int? after = default(int?), int? pageSize = default(int?), System.DateTime? fromDate = default(System.DateTime?), System.DateTime? toDate = default(System.DateTime?), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get recipients for a campaign mailing
        /// </summary>
        /// <remarks>
        /// Returns contacts to which the mailing has been sent.
        /// </remarks>
        /// <param name='encryptedMailingId'>
        /// </param>
        /// <param name='after'>
        /// </param>
        /// <param name='pageSize'>
        /// </param>
        /// <param name='fromDate'>
        /// </param>
        /// <param name='toDate'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetCampaignMailingRecipientContactsWithHttpMessagesAsync(string encryptedMailingId, int? after = default(int?), int? pageSize = default(int?), System.DateTime? fromDate = default(System.DateTime?), System.DateTime? toDate = default(System.DateTime?), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get all campaigns
        /// </summary>
        /// <remarks>
        /// Returns a list of all campaigns, including external campaign
        /// triggers. Other trigger types will not be shown.
        /// </remarks>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<Campaign>>> GetCampaignsWithHttpMessagesAsync(System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Trigger a campaign for a specific contact
        /// </summary>
        /// <remarks>
        /// Triggers a campaign for a given contact. The encryptedTriggerId
        /// can be retrieved by using the GET method /campaign/list.
        /// </remarks>
        /// <param name='encryptedTriggerId'>
        /// </param>
        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<ErrorResponse>> TriggerCampaignWithHttpMessagesAsync(string encryptedTriggerId, CampaignTriggerRequest body, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get all mailings of a campaign
        /// </summary>
        /// <remarks>
        /// Returns all mailings being sent by a given campaign. The
        /// encryptedCampaignId can be retrieved by using the GET method
        /// /campaign/list.
        /// </remarks>
        /// <param name='encryptedCampaignId'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetCampaignMailingsWithHttpMessagesAsync(string encryptedCampaignId, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Stop a campaign for a specific contact
        /// </summary>
        /// <remarks>
        /// Stops a running campaign for a given contact. The
        /// encryptedCampaignId can be retrieved by using the GET method
        /// /campaign/list.
        /// </remarks>
        /// <param name='encryptedCampaignId'>
        /// </param>
        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<ErrorResponse>> StopCampaignWithHttpMessagesAsync(string encryptedCampaignId, CampaignStopRequest body, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Add a contact
        /// </summary>
        /// <remarks>
        /// Adds a contact to Mailplus. A unique identifier "externalId" is
        /// required for each contact. Available properties can be retrieved
        /// by using the GET methode /contact/properties/list.
        /// </remarks>
        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<ErrorResponse>> InsertContactWithHttpMessagesAsync(ContactRequest body, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get bounced contacts
        /// </summary>
        /// <remarks>
        /// Returns bounced contacts within a specific period of time.
        /// </remarks>
        /// <param name='fromDate'>
        /// </param>
        /// <param name='toDate'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetBouncedContactsWithHttpMessagesAsync(System.DateTime fromDate, System.DateTime toDate, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get all properties
        /// </summary>
        /// <remarks>
        /// Returns a list of available properties that are part of a contact
        /// object.
        /// </remarks>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<Property>>> GetContactPropertiesWithHttpMessagesAsync(System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get contacts by properties
        /// </summary>
        /// <remarks>
        /// Returns a contact based on a given property value. Available
        /// properties can be retrieved by using the GET methode
        /// /contact/properties/list.
        /// </remarks>
        /// <param name='mPSearchQuery'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<Contact>>> SearchContactsWithHttpMessagesAsync(string mPSearchQuery, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get updated contacts
        /// </summary>
        /// <remarks>
        /// Returns contacts which have been updated within a specific period
        /// of time.
        /// </remarks>
        /// <param name='fromDate'>
        /// </param>
        /// <param name='toDate'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetUpdatedContactsWithHttpMessagesAsync(System.DateTime fromDate, System.DateTime toDate, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get a contact
        /// </summary>
        /// <remarks>
        /// Returns a given contact, including a list of all properties.
        /// Properties will only be shown if data is available.
        /// </remarks>
        /// <param name='externalId'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetContactWithHttpMessagesAsync(string externalId, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Update a contact
        /// </summary>
        /// <remarks>
        /// Modifies a existing given contact.
        /// </remarks>
        /// <param name='body'>
        /// </param>
        /// <param name='externalId'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<ErrorResponse>> UpdateContactWithHttpMessagesAsync(ContactRequest body, string externalId, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get campaign mailing history for a contact
        /// </summary>
        /// <remarks>
        /// Returns received campaign mailings for a given contact. Default
        /// pagesize is 50 (Cannot be modified).
        /// </remarks>
        /// <param name='externalId'>
        /// </param>
        /// <param name='after'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetContactCampaignMailingHistoryWithHttpMessagesAsync(string externalId, int? after = default(int?), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get form history for a contact
        /// </summary>
        /// <remarks>
        /// Returns submitted forms for a given contact.
        /// </remarks>
        /// <param name='externalId'>
        /// </param>
        /// <param name='after'>
        /// </param>
        /// <param name='pageSize'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetContactFormHistoryWithHttpMessagesAsync(string externalId, int? after = default(int?), int? pageSize = default(int?), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get mailing history for a contact
        /// </summary>
        /// <remarks>
        /// Returns received mailings for a given contact. Default pagesize is
        /// 50 (Cannot be modified).
        /// </remarks>
        /// <param name='externalId'>
        /// </param>
        /// <param name='after'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetContactMailingHistoryWithHttpMessagesAsync(string externalId, int? after = default(int?), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Add a conversion interaction
        /// </summary>
        /// <remarks>
        /// Posts created-, converted and abandoned shopping carts to MailPlus
        /// as a result of click in a sent mailing. The mailplusId is added
        /// to every trackable URL, that leads to your website. This ID is
        /// unique for every mailing and contact.
        /// </remarks>
        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<ErrorResponse>> CreateConversionInteractionWithHttpMessagesAsync(Conversion body, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get all forms
        /// </summary>
        /// <remarks>
        /// Returns a list all available forms.
        /// </remarks>
        /// <param name='formSubType'>
        /// Possible values include: 'normal', 'subscribe', 'unSubscribe',
        /// 'editProfile'
        /// </param>
        /// <param name='formState'>
        /// Possible values include: 'draft', 'proof', 'final'
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<Form>>> GetFormsWithHttpMessagesAsync(string formSubType = default(string), string formState = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get form results
        /// </summary>
        /// <remarks>
        /// Returns submitted results of a requested form, including all given
        /// answers for every submit.
        /// </remarks>
        /// <param name='formId'>
        /// </param>
        /// <param name='completed'>
        /// </param>
        /// <param name='startDate'>
        /// </param>
        /// <param name='endDate'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<FormResult>>> GetFormResultsWithHttpMessagesAsync(int formId, bool? completed = default(bool?), System.DateTime? startDate = default(System.DateTime?), System.DateTime? endDate = default(System.DateTime?), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Post a form result
        /// </summary>
        /// <remarks>
        /// Submits a form response to a MailPlus form. The post URL needs to
        /// refer to your own system.
        /// </remarks>
        /// <param name='formId'>
        /// </param>
        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<FormResponse>> SubmitFormWithHttpMessagesAsync(int formId, ParamsModel body, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get form result
        /// </summary>
        /// <remarks>
        /// Returns a submitted result of a requested form for a given
        /// formResultId. A formResultId can be retrieved by using the GET
        /// method /contact/{externalId}/forms.
        /// </remarks>
        /// <param name='formId'>
        /// </param>
        /// <param name='formResultId'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetFormResultWithHttpMessagesAsync(int formId, int formResultId, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get a form
        /// </summary>
        /// <remarks>
        /// Returns a HTML output of the requested form.
        /// </remarks>
        /// <param name='formId'>
        /// </param>
        /// <param name='postUrl'>
        /// </param>
        /// <param name='encId'>
        /// Unique (MailPlus) id of a contact (when present the form is
        /// prefilled with contact fields)
        /// </param>
        /// <param name='extraParams'>
        /// </param>
        /// <param name='outputFormat'>
        /// Possible values include: 'HTML4STRICT', 'XHTML1STRICT'
        /// </param>
        /// <param name='outputMode'>
        /// Possible values include: 'TABLES', 'DIV'
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetFormWithHttpMessagesAsync(int formId, string postUrl, string encId = default(string), string extraParams = default(string), string outputFormat = "HTML4STRICT", string outputMode = "TABLES", System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Post a form
        /// </summary>
        /// <remarks>
        /// Returns a prefilled HTML output of a requested form, based on the
        /// given parameters for a specific contact.  If a contact is present
        /// in MailPlus, existing data will be prefilled in de used contact
        /// fields. The post URL needs to refer to your own system.
        /// </remarks>
        /// <param name='formId'>
        /// </param>
        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> PostFormWithHttpMessagesAsync(int formId, FormRequest body, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get sent mailings in period
        /// </summary>
        /// <remarks>
        /// Returns a list of all mailings, including a link to the archived
        /// online version of the sent mailing.
        /// </remarks>
        /// <param name='fromDate'>
        /// </param>
        /// <param name='toDate'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetMailingsWithHttpMessagesAsync(System.DateTime fromDate, System.DateTime toDate, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get mailing data
        /// </summary>
        /// <remarks>
        /// Returns the details of a given mailing, including details of the
        /// used links.
        /// </remarks>
        /// <param name='encryptedMailingId'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetMailingDetailsWithHttpMessagesAsync(string encryptedMailingId, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get bounces for mailing
        /// </summary>
        /// <remarks>
        /// Returns bounced contacts.
        /// </remarks>
        /// <param name='encryptedMailingId'>
        /// </param>
        /// <param name='after'>
        /// </param>
        /// <param name='pageSize'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetMailingBouncesWithHttpMessagesAsync(string encryptedMailingId, int? after = default(int?), int? pageSize = default(int?), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get clicks for mailing
        /// </summary>
        /// <remarks>
        /// Returns contacts who clicked a link in a given mailing. Link
        /// details can be retrieved by using the GET method
        /// /mailing/{encryptedMailingId}.
        /// </remarks>
        /// <param name='encryptedMailingId'>
        /// </param>
        /// <param name='after'>
        /// </param>
        /// <param name='pageSize'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetMailingClicksWithHttpMessagesAsync(string encryptedMailingId, int? after = default(int?), int? pageSize = default(int?), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get clicks of a mailing for a contact
        /// </summary>
        /// <remarks>
        /// Returns click interactions for a given contact in a specified
        /// mailing. Link details can be retrieved by using the GET method
        /// /mailing/{encryptedMailingId}.
        /// </remarks>
        /// <param name='encryptedMailingId'>
        /// </param>
        /// <param name='externalId'>
        /// </param>
        /// <param name='after'>
        /// </param>
        /// <param name='pageSize'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetMailingContactClicksWithHttpMessagesAsync(string encryptedMailingId, string externalId, int? after = default(int?), int? pageSize = default(int?), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get opens for mailing
        /// </summary>
        /// <remarks>
        /// Returns contacts who opened a given mailing.
        /// </remarks>
        /// <param name='encryptedMailingId'>
        /// </param>
        /// <param name='after'>
        /// </param>
        /// <param name='pageSize'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetMailingOpensWithHttpMessagesAsync(string encryptedMailingId, int? after = default(int?), int? pageSize = default(int?), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get opens of a mailing for a contact
        /// </summary>
        /// <remarks>
        /// Returns open interations for a given contact in a specified
        /// mailing.
        /// </remarks>
        /// <param name='encryptedMailingId'>
        /// </param>
        /// <param name='externalId'>
        /// </param>
        /// <param name='after'>
        /// </param>
        /// <param name='pageSize'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetMailingContactOpensWithHttpMessagesAsync(string encryptedMailingId, string externalId, int? after = default(int?), int? pageSize = default(int?), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get recipients for mailing
        /// </summary>
        /// <remarks>
        /// Returns contacts to which the mailing has been sent.
        /// </remarks>
        /// <param name='encryptedMailingId'>
        /// </param>
        /// <param name='after'>
        /// </param>
        /// <param name='pageSize'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetMailingRecipientContactsWithHttpMessagesAsync(string encryptedMailingId, int? after = default(int?), int? pageSize = default(int?), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get mailing statistics
        /// </summary>
        /// <remarks>
        /// Returns a summary of the results for a sent mailing, such as the
        /// opens, clicks, bounces, etc.
        /// </remarks>
        /// <param name='encryptedMailingId'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetMailingStatsWithHttpMessagesAsync(string encryptedMailingId, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Add an order
        /// </summary>
        /// <remarks>
        /// Adds an order to MailPlus.
        /// </remarks>
        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<ErrorResponse>> InsertOrderWithHttpMessagesAsync(OrderRequest body, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Delete an order
        /// </summary>
        /// <remarks>
        /// Deletes an existing order.
        /// </remarks>
        /// <param name='externalOrderId'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<ErrorResponse>> DeleteOrderWithHttpMessagesAsync(string externalOrderId, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Update an order
        /// </summary>
        /// <remarks>
        /// Updates an existing order.
        /// </remarks>
        /// <param name='externalOrderId'>
        /// </param>
        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<ErrorResponse>> UpdateOrderWithHttpMessagesAsync(string externalOrderId, OrderRequest body, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Add a product
        /// </summary>
        /// <remarks>
        /// Adds a product to MailPlus.
        /// </remarks>
        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<ErrorResponse>> InsertProductWithHttpMessagesAsync(ProductRequest body, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Delete a product
        /// </summary>
        /// <remarks>
        /// Deletes an existing given product.
        /// </remarks>
        /// <param name='externalProductId'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<ErrorResponse>> DeleteProductWithHttpMessagesAsync(string externalProductId, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get a product
        /// </summary>
        /// <remarks>
        /// Returns a given product.
        /// </remarks>
        /// <param name='externalProductId'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<object>> GetProductWithHttpMessagesAsync(string externalProductId, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Update a product
        /// </summary>
        /// <remarks>
        /// Updates an existing given product.
        /// </remarks>
        /// <param name='externalProductId'>
        /// </param>
        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<ErrorResponse>> UpdateProductWithHttpMessagesAsync(string externalProductId, ProductRequest body, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Subscribe a contact
        /// </summary>
        /// <remarks>
        /// Adds a contact to Mailplus. A unique identifier "externalId" is
        /// NOT required. Available properties can be retrieved by using the
        /// GET methode /contact/properties/list.
        /// </remarks>
        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<ErrorResponse>> SubscribeContactWithHttpMessagesAsync(Contact body, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get all temporary lists
        /// </summary>
        /// <remarks>
        /// Returns a list of all available temporary lists.
        /// </remarks>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<TemporaryList>>> GetTemporaryListsWithHttpMessagesAsync(System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Add a temporary list
        /// </summary>
        /// <remarks>
        /// Adds a set of existing contacts as a temporary list to MailPlus,
        /// based on external contact id's.
        /// </remarks>
        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<ErrorResponse>> CreateTemporaryListWithHttpMessagesAsync(CreateTemporaryListRequest body, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Delete a temporary list
        /// </summary>
        /// <remarks>
        /// Deletes a temporary list. An externalTemporaryListId can be
        /// retrieved by using the GET method /templist.
        /// </remarks>
        /// <param name='externalTemporaryListId'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<ErrorResponse>> DeleteTemporaryListWithHttpMessagesAsync(string externalTemporaryListId, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Add contacts to a temporary list
        /// </summary>
        /// <remarks>
        /// Adds a set of existing contacts to a given temporary list, based
        /// on external contact id's. An externalTemporaryListId can be
        /// retrieved by using the GET method /templist.
        /// </remarks>
        /// <param name='externalTemporaryListId'>
        /// </param>
        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<ErrorResponse>> AddContactsToTemporaryListWithHttpMessagesAsync(string externalTemporaryListId, AddContactsToTemporaryListRequest body, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

    }
}
