// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AddContactsToTemporaryListRequest
    {
        /// <summary>
        /// Initializes a new instance of the
        /// AddContactsToTemporaryListRequest class.
        /// </summary>
        public AddContactsToTemporaryListRequest() { }

        /// <summary>
        /// Initializes a new instance of the
        /// AddContactsToTemporaryListRequest class.
        /// </summary>
        public AddContactsToTemporaryListRequest(IList<string> contacts)
        {
            Contacts = contacts;
        }

        /// <summary>
        /// List of externalContactId's
        /// </summary>
        [JsonProperty(PropertyName = "contacts")]
        public IList<string> Contacts { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Contacts == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Contacts");
            }
        }
    }
}
