// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class CampaignMailingBounceResponse
    {
        /// <summary>
        /// Initializes a new instance of the CampaignMailingBounceResponse
        /// class.
        /// </summary>
        public CampaignMailingBounceResponse() { }

        /// <summary>
        /// Initializes a new instance of the CampaignMailingBounceResponse
        /// class.
        /// </summary>
        public CampaignMailingBounceResponse(System.Collections.Generic.IList<CampaignMailingBounce> bounces = default(System.Collections.Generic.IList<CampaignMailingBounce>), Paging paging = default(Paging))
        {
            Bounces = bounces;
            Paging = paging;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "bounces")]
        public System.Collections.Generic.IList<CampaignMailingBounce> Bounces { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "paging")]
        public Paging Paging { get; set; }

    }
}
