// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CampaignMailingOpen
    {
        /// <summary>
        /// Initializes a new instance of the CampaignMailingOpen class.
        /// </summary>
        public CampaignMailingOpen() { }

        /// <summary>
        /// Initializes a new instance of the CampaignMailingOpen class.
        /// </summary>
        public CampaignMailingOpen(int campaignSubscriptionId, ContactIdentifier contactIdentifier, DateTime openDate)
        {
            CampaignSubscriptionId = campaignSubscriptionId;
            ContactIdentifier = contactIdentifier;
            OpenDate = openDate;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "campaignSubscriptionId")]
        public int CampaignSubscriptionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contactIdentifier")]
        public ContactIdentifier ContactIdentifier { get; set; }

        /// <summary>
        /// Date &amp; time the open occurred
        /// </summary>
        [JsonProperty(PropertyName = "openDate")]
        public DateTime OpenDate { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (ContactIdentifier == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ContactIdentifier");
            }
            if (this.ContactIdentifier != null)
            {
                this.ContactIdentifier.Validate();
            }
        }
    }
}
