// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class CampaignTrigger
    {
        /// <summary>
        /// Initializes a new instance of the CampaignTrigger class.
        /// </summary>
        public CampaignTrigger() { }

        /// <summary>
        /// Initializes a new instance of the CampaignTrigger class.
        /// </summary>
        /// <param name="encryptedId">encryptedTriggerId</param>
        /// <param name="name">Trigger name</param>
        public CampaignTrigger(string encryptedId, string name)
        {
            EncryptedId = encryptedId;
            Name = name;
        }

        /// <summary>
        /// Gets or sets encryptedTriggerId
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "encryptedId")]
        public string EncryptedId { get; set; }

        /// <summary>
        /// Gets or sets trigger name
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (EncryptedId == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "EncryptedId");
            }
            if (Name == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
