// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CampaignField
    {
        /// <summary>
        /// Initializes a new instance of the CampaignField class.
        /// </summary>
        public CampaignField() { }

        /// <summary>
        /// Initializes a new instance of the CampaignField class.
        /// </summary>
        public CampaignField(string name, string type = default(string), string value = default(string), IList<string> values = default(IList<string>))
        {
            Name = name;
            Type = type;
            Value = value;
            Values = values;
        }

        /// <summary>
        /// Placeholder name used in campaign mailing
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Default: STRING. Possible values include: 'STRING', 'PRODUCTLIST'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Used by the string campaignfield
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// Used by the productlist campaignfield to post multiple product
        /// references
        /// </summary>
        [JsonProperty(PropertyName = "values")]
        public IList<string> Values { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
