// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class CampaignMailingDetails
    {
        /// <summary>
        /// Initializes a new instance of the CampaignMailingDetails class.
        /// </summary>
        public CampaignMailingDetails() { }

        /// <summary>
        /// Initializes a new instance of the CampaignMailingDetails class.
        /// </summary>
        /// <param name="encryptedId">encryptedMailingId (Use
        /// '/campaign-mailing/*' to request additional data)</param>
        /// <param name="name">Campaign mailing name</param>
        /// <param name="type">Possible values include: 'EMAIL', 'SMS'</param>
        public CampaignMailingDetails(string encryptedId, Message message, string name, string type, System.Collections.Generic.IList<MailingLink> links = default(System.Collections.Generic.IList<MailingLink>))
        {
            EncryptedId = encryptedId;
            Links = links;
            Message = message;
            Name = name;
            Type = type;
        }

        /// <summary>
        /// Gets or sets encryptedMailingId (Use '/campaign-mailing/*' to
        /// request additional data)
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "encryptedId")]
        public string EncryptedId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "links")]
        public System.Collections.Generic.IList<MailingLink> Links { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "message")]
        public Message Message { get; set; }

        /// <summary>
        /// Gets or sets campaign mailing name
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'EMAIL', 'SMS'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (EncryptedId == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "EncryptedId");
            }
            if (Message == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Message");
            }
            if (Name == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Name");
            }
            if (Type == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Type");
            }
            if (this.Links != null)
            {
                foreach (var element in this.Links)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
            if (this.Message != null)
            {
                this.Message.Validate();
            }
        }
    }
}
