// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CampaignMailingRecipientResponse
    {
        /// <summary>
        /// Initializes a new instance of the CampaignMailingRecipientResponse
        /// class.
        /// </summary>
        public CampaignMailingRecipientResponse() { }

        /// <summary>
        /// Initializes a new instance of the CampaignMailingRecipientResponse
        /// class.
        /// </summary>
        public CampaignMailingRecipientResponse(Paging paging = default(Paging), IList<CampaignMailingRecipient> recipients = default(IList<CampaignMailingRecipient>))
        {
            Paging = paging;
            Recipients = recipients;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paging")]
        public Paging Paging { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recipients")]
        public IList<CampaignMailingRecipient> Recipients { get; set; }

    }
}
