// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CampaignMailingBounceResponse
    {
        /// <summary>
        /// Initializes a new instance of the CampaignMailingBounceResponse
        /// class.
        /// </summary>
        public CampaignMailingBounceResponse() { }

        /// <summary>
        /// Initializes a new instance of the CampaignMailingBounceResponse
        /// class.
        /// </summary>
        public CampaignMailingBounceResponse(IList<CampaignMailingBounce> bounces = default(IList<CampaignMailingBounce>), Paging paging = default(Paging))
        {
            Bounces = bounces;
            Paging = paging;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bounces")]
        public IList<CampaignMailingBounce> Bounces { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paging")]
        public Paging Paging { get; set; }

    }
}
