// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class CampaignMailingClickResponse
    {
        /// <summary>
        /// Initializes a new instance of the CampaignMailingClickResponse
        /// class.
        /// </summary>
        public CampaignMailingClickResponse() { }

        /// <summary>
        /// Initializes a new instance of the CampaignMailingClickResponse
        /// class.
        /// </summary>
        public CampaignMailingClickResponse(System.Collections.Generic.IList<CampaignMailingClick> clicks = default(System.Collections.Generic.IList<CampaignMailingClick>), Paging paging = default(Paging))
        {
            Clicks = clicks;
            Paging = paging;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "clicks")]
        public System.Collections.Generic.IList<CampaignMailingClick> Clicks { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "paging")]
        public Paging Paging { get; set; }

    }
}
