// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class CampaignMailingHistoryResponse
    {
        /// <summary>
        /// Initializes a new instance of the CampaignMailingHistoryResponse
        /// class.
        /// </summary>
        public CampaignMailingHistoryResponse() { }

        /// <summary>
        /// Initializes a new instance of the CampaignMailingHistoryResponse
        /// class.
        /// </summary>
        public CampaignMailingHistoryResponse(System.Collections.Generic.IList<CampaignMailingHistory> campaignMailingHistories = default(System.Collections.Generic.IList<CampaignMailingHistory>), Paging paging = default(Paging))
        {
            CampaignMailingHistories = campaignMailingHistories;
            Paging = paging;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "campaignMailingHistories")]
        public System.Collections.Generic.IList<CampaignMailingHistory> CampaignMailingHistories { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "paging")]
        public Paging Paging { get; set; }

    }
}
