// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class CampaignMailingRecipientResponse
    {
        /// <summary>
        /// Initializes a new instance of the CampaignMailingRecipientResponse
        /// class.
        /// </summary>
        public CampaignMailingRecipientResponse() { }

        /// <summary>
        /// Initializes a new instance of the CampaignMailingRecipientResponse
        /// class.
        /// </summary>
        public CampaignMailingRecipientResponse(Paging paging = default(Paging), System.Collections.Generic.IList<CampaignMailingRecipient> recipients = default(System.Collections.Generic.IList<CampaignMailingRecipient>))
        {
            Paging = paging;
            Recipients = recipients;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "paging")]
        public Paging Paging { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "recipients")]
        public System.Collections.Generic.IList<CampaignMailingRecipient> Recipients { get; set; }

    }
}
