// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CampaignMailingDetails
    {
        /// <summary>
        /// Initializes a new instance of the CampaignMailingDetails class.
        /// </summary>
        public CampaignMailingDetails() { }

        /// <summary>
        /// Initializes a new instance of the CampaignMailingDetails class.
        /// </summary>
        public CampaignMailingDetails(string encryptedId, Message message, string name, string type, IList<MailingLink> links = default(IList<MailingLink>))
        {
            EncryptedId = encryptedId;
            Links = links;
            Message = message;
            Name = name;
            Type = type;
        }

        /// <summary>
        /// encryptedMailingId (Use '/campaign-mailing/*' to request
        /// additional data)
        /// </summary>
        [JsonProperty(PropertyName = "encryptedId")]
        public string EncryptedId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "links")]
        public IList<MailingLink> Links { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public Message Message { get; set; }

        /// <summary>
        /// Campaign mailing name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Possible values include: 'EMAIL', 'SMS'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (EncryptedId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "EncryptedId");
            }
            if (Message == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Message");
            }
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (Type == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Type");
            }
            if (this.Links != null)
            {
                foreach (var element in this.Links)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
            if (this.Message != null)
            {
                this.Message.Validate();
            }
        }
    }
}
