// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class CampaignMailingOpenResponse
    {
        /// <summary>
        /// Initializes a new instance of the CampaignMailingOpenResponse
        /// class.
        /// </summary>
        public CampaignMailingOpenResponse() { }

        /// <summary>
        /// Initializes a new instance of the CampaignMailingOpenResponse
        /// class.
        /// </summary>
        public CampaignMailingOpenResponse(System.Collections.Generic.IList<CampaignMailingOpen> opens = default(System.Collections.Generic.IList<CampaignMailingOpen>), Paging paging = default(Paging))
        {
            Opens = opens;
            Paging = paging;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "opens")]
        public System.Collections.Generic.IList<CampaignMailingOpen> Opens { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "paging")]
        public Paging Paging { get; set; }

    }
}
