// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class CampaignMailing
    {
        /// <summary>
        /// Initializes a new instance of the CampaignMailing class.
        /// </summary>
        public CampaignMailing() { }

        /// <summary>
        /// Initializes a new instance of the CampaignMailing class.
        /// </summary>
        /// <param name="encryptedId">encryptedMailingId (Use
        /// '/campaign-mailing/*' to request additional data)</param>
        /// <param name="name">Campaign mailing name</param>
        /// <param name="type">Possible values include: 'EMAIL', 'SMS'</param>
        public CampaignMailing(string encryptedId, string name, string type)
        {
            EncryptedId = encryptedId;
            Name = name;
            Type = type;
        }

        /// <summary>
        /// Gets or sets encryptedMailingId (Use '/campaign-mailing/*' to
        /// request additional data)
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "encryptedId")]
        public string EncryptedId { get; set; }

        /// <summary>
        /// Gets or sets campaign mailing name
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'EMAIL', 'SMS'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (EncryptedId == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "EncryptedId");
            }
            if (Name == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Name");
            }
            if (Type == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Type");
            }
        }
    }
}
