// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Campaign
    {
        /// <summary>
        /// Initializes a new instance of the Campaign class.
        /// </summary>
        public Campaign() { }

        /// <summary>
        /// Initializes a new instance of the Campaign class.
        /// </summary>
        public Campaign(bool active, string encryptedId, string name, IList<CampaignTrigger> triggers = default(IList<CampaignTrigger>))
        {
            Active = active;
            EncryptedId = encryptedId;
            Name = name;
            Triggers = triggers;
        }

        /// <summary>
        /// Campaign status
        /// </summary>
        [JsonProperty(PropertyName = "active")]
        public bool Active { get; set; }

        /// <summary>
        /// encryptedCampaignId
        /// </summary>
        [JsonProperty(PropertyName = "encryptedId")]
        public string EncryptedId { get; set; }

        /// <summary>
        /// Campaign name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "triggers")]
        public IList<CampaignTrigger> Triggers { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (EncryptedId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "EncryptedId");
            }
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (this.Triggers != null)
            {
                foreach (var element in this.Triggers)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
