// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class ContactRequest
    {
        /// <summary>
        /// Initializes a new instance of the ContactRequest class.
        /// </summary>
        public ContactRequest() { }

        /// <summary>
        /// Initializes a new instance of the ContactRequest class.
        /// </summary>
        /// <param name="purge">Existing properties will be purged if not set
        /// - Default value: false</param>
        /// <param name="update">Only existing contacts can be updated -
        /// Default value: false</param>
        public ContactRequest(Contact contact, bool? purge = default(bool?), bool? update = default(bool?))
        {
            Contact = contact;
            Purge = purge;
            Update = update;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "contact")]
        public Contact Contact { get; set; }

        /// <summary>
        /// Gets or sets existing properties will be purged if not set -
        /// Default value: false
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "purge")]
        public bool? Purge { get; set; }

        /// <summary>
        /// Gets or sets only existing contacts can be updated - Default
        /// value: false
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "update")]
        public bool? Update { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Contact == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Contact");
            }
            if (this.Contact != null)
            {
                this.Contact.Validate();
            }
        }
    }
}
