// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ContactRequest
    {
        /// <summary>
        /// Initializes a new instance of the ContactRequest class.
        /// </summary>
        public ContactRequest() { }

        /// <summary>
        /// Initializes a new instance of the ContactRequest class.
        /// </summary>
        public ContactRequest(Contact contact, bool? purge = default(bool?), bool? update = default(bool?))
        {
            Contact = contact;
            Purge = purge;
            Update = update;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contact")]
        public Contact Contact { get; set; }

        /// <summary>
        /// Existing properties will be purged if not set - Default value:
        /// false
        /// </summary>
        [JsonProperty(PropertyName = "purge")]
        public bool? Purge { get; set; }

        /// <summary>
        /// Only existing contacts can be updated - Default value: false
        /// </summary>
        [JsonProperty(PropertyName = "update")]
        public bool? Update { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Contact == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Contact");
            }
            if (this.Contact != null)
            {
                this.Contact.Validate();
            }
        }
    }
}
