// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ContactIdentifier
    {
        /// <summary>
        /// Initializes a new instance of the ContactIdentifier class.
        /// </summary>
        public ContactIdentifier() { }

        /// <summary>
        /// Initializes a new instance of the ContactIdentifier class.
        /// </summary>
        public ContactIdentifier(string encryptedId, string externalId = default(string))
        {
            EncryptedId = encryptedId;
            ExternalId = externalId;
        }

        /// <summary>
        /// Contact reference generated by MailPlus
        /// </summary>
        [JsonProperty(PropertyName = "encryptedId")]
        public string EncryptedId { get; set; }

        /// <summary>
        /// Specified contact reference by external system
        /// </summary>
        [JsonProperty(PropertyName = "externalId")]
        public string ExternalId { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (EncryptedId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "EncryptedId");
            }
        }
    }
}
