// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class Conversion
    {
        /// <summary>
        /// Initializes a new instance of the Conversion class.
        /// </summary>
        public Conversion() { }

        /// <summary>
        /// Initializes a new instance of the Conversion class.
        /// </summary>
        /// <param name="interactionDate">Date & time the shopping cart was
        /// created</param>
        /// <param name="mailplusId">reference generated by MailPlus to add
        /// conversion details to a mailing report</param>
        /// <param name="type">Possible values include: 'CREATE_SHOPPINGCART',
        /// ' CONVERT_SHOPPINGCART'</param>
        /// <param name="products">Products part of the order/shopping
        /// cart</param>
        /// <param name="value">Total order value in cents</param>
        public Conversion(System.DateTime interactionDate, string mailplusId, string type, System.Collections.Generic.IList<string> products = default(System.Collections.Generic.IList<string>), string value = default(string))
        {
            InteractionDate = interactionDate;
            MailplusId = mailplusId;
            Products = products;
            Type = type;
            Value = value;
        }

        /// <summary>
        /// Gets or sets date &amp; time the shopping cart was created
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "interactionDate")]
        public System.DateTime InteractionDate { get; set; }

        /// <summary>
        /// Gets or sets reference generated by MailPlus to add conversion
        /// details to a mailing report
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "mailplusId")]
        public string MailplusId { get; set; }

        /// <summary>
        /// Gets or sets products part of the order/shopping cart
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "products")]
        public System.Collections.Generic.IList<string> Products { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'CREATE_SHOPPINGCART', '
        /// CONVERT_SHOPPINGCART'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets total order value in cents
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (MailplusId == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "MailplusId");
            }
            if (Type == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Type");
            }
        }
    }
}
