// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Conversion
    {
        /// <summary>
        /// Initializes a new instance of the Conversion class.
        /// </summary>
        public Conversion() { }

        /// <summary>
        /// Initializes a new instance of the Conversion class.
        /// </summary>
        public Conversion(DateTime interactionDate, string mailplusId, string type, IList<string> products = default(IList<string>), string value = default(string))
        {
            InteractionDate = interactionDate;
            MailplusId = mailplusId;
            Products = products;
            Type = type;
            Value = value;
        }

        /// <summary>
        /// Date &amp; time the shopping cart was created
        /// </summary>
        [JsonProperty(PropertyName = "interactionDate")]
        public DateTime InteractionDate { get; set; }

        /// <summary>
        /// reference generated by MailPlus to add conversion details to a
        /// mailing report
        /// </summary>
        [JsonProperty(PropertyName = "mailplusId")]
        public string MailplusId { get; set; }

        /// <summary>
        /// Products part of the order/shopping cart
        /// </summary>
        [JsonProperty(PropertyName = "products")]
        public IList<string> Products { get; set; }

        /// <summary>
        /// Possible values include: 'CREATE_SHOPPINGCART', '
        /// CONVERT_SHOPPINGCART'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Total order value in cents
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (MailplusId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "MailplusId");
            }
            if (Type == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Type");
            }
        }
    }
}
