// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class CreateTemporaryListRequest
    {
        /// <summary>
        /// Initializes a new instance of the CreateTemporaryListRequest class.
        /// </summary>
        public CreateTemporaryListRequest() { }

        /// <summary>
        /// Initializes a new instance of the CreateTemporaryListRequest class.
        /// </summary>
        /// <param name="externalTemporaryListId">Specified list reference by
        /// external system</param>
        /// <param name="name">Temporary list name visible in MailPlus</param>
        /// <param name="contacts">List of externalContactId's</param>
        public CreateTemporaryListRequest(string externalTemporaryListId, string name, System.Collections.Generic.IList<string> contacts = default(System.Collections.Generic.IList<string>))
        {
            Contacts = contacts;
            ExternalTemporaryListId = externalTemporaryListId;
            Name = name;
        }

        /// <summary>
        /// Gets or sets list of externalContactId's
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "contacts")]
        public System.Collections.Generic.IList<string> Contacts { get; set; }

        /// <summary>
        /// Gets or sets specified list reference by external system
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "externalTemporaryListId")]
        public string ExternalTemporaryListId { get; set; }

        /// <summary>
        /// Gets or sets temporary list name visible in MailPlus
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ExternalTemporaryListId == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "ExternalTemporaryListId");
            }
            if (Name == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
