// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CreateTemporaryListRequest
    {
        /// <summary>
        /// Initializes a new instance of the CreateTemporaryListRequest class.
        /// </summary>
        public CreateTemporaryListRequest() { }

        /// <summary>
        /// Initializes a new instance of the CreateTemporaryListRequest class.
        /// </summary>
        public CreateTemporaryListRequest(string externalTemporaryListId, string name, IList<string> contacts = default(IList<string>))
        {
            Contacts = contacts;
            ExternalTemporaryListId = externalTemporaryListId;
            Name = name;
        }

        /// <summary>
        /// List of externalContactId's
        /// </summary>
        [JsonProperty(PropertyName = "contacts")]
        public IList<string> Contacts { get; set; }

        /// <summary>
        /// Specified list reference by external system
        /// </summary>
        [JsonProperty(PropertyName = "externalTemporaryListId")]
        public string ExternalTemporaryListId { get; set; }

        /// <summary>
        /// Temporary list name visible in MailPlus
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (ExternalTemporaryListId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ExternalTemporaryListId");
            }
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
