// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class FormHistory
    {
        /// <summary>
        /// Initializes a new instance of the FormHistory class.
        /// </summary>
        public FormHistory() { }

        /// <summary>
        /// Initializes a new instance of the FormHistory class.
        /// </summary>
        /// <param name="formResultId">(Use '/form/result*' to request
        /// additional data)</param>
        /// <param name="submitDate">Date & time the form was submitted</param>
        public FormHistory(bool completed, Form form, int formResultId, System.DateTime submitDate)
        {
            Completed = completed;
            Form = form;
            FormResultId = formResultId;
            SubmitDate = submitDate;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "completed")]
        public bool Completed { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "form")]
        public Form Form { get; set; }

        /// <summary>
        /// Gets or sets (Use '/form/result*' to request additional data)
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "formResultId")]
        public int FormResultId { get; set; }

        /// <summary>
        /// Gets or sets date &amp; time the form was submitted
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "submitDate")]
        public System.DateTime SubmitDate { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Form == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Form");
            }
            if (this.Form != null)
            {
                this.Form.Validate();
            }
        }
    }
}
