// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class FormResult
    {
        /// <summary>
        /// Initializes a new instance of the FormResult class.
        /// </summary>
        public FormResult() { }

        /// <summary>
        /// Initializes a new instance of the FormResult class.
        /// </summary>
        /// <param name="formResultId">(Use '/form/result*' to request
        /// additional data)</param>
        /// <param name="submittedAt">Date & time the form was
        /// submitted</param>
        /// <param name="testResult">Test results only occur when the
        /// formState is not final</param>
        /// <param name="answers">All form questions and answers if
        /// available</param>
        public FormResult(bool completed, int formResultId, System.DateTime submittedAt, bool testResult, System.Collections.Generic.IList<FormElementResult> answers = default(System.Collections.Generic.IList<FormElementResult>))
        {
            Answers = answers;
            Completed = completed;
            FormResultId = formResultId;
            SubmittedAt = submittedAt;
            TestResult = testResult;
        }

        /// <summary>
        /// Gets or sets all form questions and answers if available
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "answers")]
        public System.Collections.Generic.IList<FormElementResult> Answers { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "completed")]
        public bool Completed { get; set; }

        /// <summary>
        /// Gets or sets (Use '/form/result*' to request additional data)
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "formResultId")]
        public int FormResultId { get; set; }

        /// <summary>
        /// Gets or sets date &amp; time the form was submitted
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "submittedAt")]
        public System.DateTime SubmittedAt { get; set; }

        /// <summary>
        /// Gets or sets test results only occur when the formState is not
        /// final
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "testResult")]
        public bool TestResult { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (this.Answers != null)
            {
                foreach (var element in this.Answers)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
