// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FormHistory
    {
        /// <summary>
        /// Initializes a new instance of the FormHistory class.
        /// </summary>
        public FormHistory() { }

        /// <summary>
        /// Initializes a new instance of the FormHistory class.
        /// </summary>
        public FormHistory(bool completed, Form form, int formResultId, DateTime submitDate)
        {
            Completed = completed;
            Form = form;
            FormResultId = formResultId;
            SubmitDate = submitDate;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "completed")]
        public bool Completed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "form")]
        public Form Form { get; set; }

        /// <summary>
        /// (Use '/form/result*' to request additional data)
        /// </summary>
        [JsonProperty(PropertyName = "formResultId")]
        public int FormResultId { get; set; }

        /// <summary>
        /// Date &amp; time the form was submitted
        /// </summary>
        [JsonProperty(PropertyName = "submitDate")]
        public DateTime SubmitDate { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Form == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Form");
            }
            if (this.Form != null)
            {
                this.Form.Validate();
            }
        }
    }
}
