// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FormResponse
    {
        /// <summary>
        /// Initializes a new instance of the FormResponse class.
        /// </summary>
        public FormResponse() { }

        /// <summary>
        /// Initializes a new instance of the FormResponse class.
        /// </summary>
        public FormResponse(string html = default(string), bool? isConfirmationPage = default(bool?), string script = default(string), string url = default(string))
        {
            Html = html;
            IsConfirmationPage = isConfirmationPage;
            Script = script;
            Url = url;
        }

        /// <summary>
        /// HTML form
        /// </summary>
        [JsonProperty(PropertyName = "html")]
        public string Html { get; set; }

        /// <summary>
        /// Indicates whether the requested form is a confirmation page
        /// </summary>
        [JsonProperty(PropertyName = "isConfirmationPage")]
        public bool? IsConfirmationPage { get; set; }

        /// <summary>
        /// Validation scripts
        /// </summary>
        [JsonProperty(PropertyName = "script")]
        public string Script { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

    }
}
