// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FormRequest
    {
        /// <summary>
        /// Initializes a new instance of the FormRequest class.
        /// </summary>
        public FormRequest() { }

        /// <summary>
        /// Initializes a new instance of the FormRequest class.
        /// </summary>
        public FormRequest(string postUrl, string encId = default(string), string extraParams = default(string), string outputFormat = default(string), string outputMode = default(string), IDictionary<string, IList<string>> prefilledValues = default(IDictionary<string, IList<string>>))
        {
            EncId = encId;
            ExtraParams = extraParams;
            OutputFormat = outputFormat;
            OutputMode = outputMode;
            PostUrl = postUrl;
            PrefilledValues = prefilledValues;
        }

        /// <summary>
        /// Form reference generated by MailPlus
        /// </summary>
        [JsonProperty(PropertyName = "encId")]
        public string EncId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "extraParams")]
        public string ExtraParams { get; set; }

        /// <summary>
        /// Default value: HTML4STRICT. Possible values include:
        /// 'HTML4STRICT', 'XHTML1STRICT'
        /// </summary>
        [JsonProperty(PropertyName = "outputFormat")]
        public string OutputFormat { get; set; }

        /// <summary>
        /// Default value: TABLES. Possible values include: 'TABLES', 'DIV'
        /// </summary>
        [JsonProperty(PropertyName = "outputMode")]
        public string OutputMode { get; set; }

        /// <summary>
        /// Form action URL
        /// </summary>
        [JsonProperty(PropertyName = "postUrl")]
        public string PostUrl { get; set; }

        /// <summary>
        /// Given values will be prefilled in the HTML output
        /// </summary>
        [JsonProperty(PropertyName = "prefilledValues")]
        public IDictionary<string, IList<string>> PrefilledValues { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (PostUrl == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "PostUrl");
            }
        }
    }
}
