// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class FormHistoryResponse
    {
        /// <summary>
        /// Initializes a new instance of the FormHistoryResponse class.
        /// </summary>
        public FormHistoryResponse() { }

        /// <summary>
        /// Initializes a new instance of the FormHistoryResponse class.
        /// </summary>
        public FormHistoryResponse(System.Collections.Generic.IList<FormHistory> formHistories = default(System.Collections.Generic.IList<FormHistory>), Paging paging = default(Paging))
        {
            FormHistories = formHistories;
            Paging = paging;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "formHistories")]
        public System.Collections.Generic.IList<FormHistory> FormHistories { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "paging")]
        public Paging Paging { get; set; }

    }
}
