// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FormHistoryResponse
    {
        /// <summary>
        /// Initializes a new instance of the FormHistoryResponse class.
        /// </summary>
        public FormHistoryResponse() { }

        /// <summary>
        /// Initializes a new instance of the FormHistoryResponse class.
        /// </summary>
        public FormHistoryResponse(IList<FormHistory> formHistories = default(IList<FormHistory>), Paging paging = default(Paging))
        {
            FormHistories = formHistories;
            Paging = paging;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "formHistories")]
        public IList<FormHistory> FormHistories { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paging")]
        public Paging Paging { get; set; }

    }
}
