// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FormElementResult
    {
        /// <summary>
        /// Initializes a new instance of the FormElementResult class.
        /// </summary>
        public FormElementResult() { }

        /// <summary>
        /// Initializes a new instance of the FormElementResult class.
        /// </summary>
        public FormElementResult(string description, int fieldId, int rank, IList<string> answer = default(IList<string>))
        {
            Answer = answer;
            Description = description;
            FieldId = fieldId;
            Rank = rank;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "answer")]
        public IList<string> Answer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fieldId")]
        public int FieldId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rank")]
        public int Rank { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Description == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Description");
            }
        }
    }
}
