// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class FormResponse
    {
        /// <summary>
        /// Initializes a new instance of the FormResponse class.
        /// </summary>
        public FormResponse() { }

        /// <summary>
        /// Initializes a new instance of the FormResponse class.
        /// </summary>
        /// <param name="html">HTML form</param>
        /// <param name="isConfirmationPage">Indicates whether the requested
        /// form is a confirmation page</param>
        /// <param name="script">Validation scripts</param>
        public FormResponse(string html = default(string), bool? isConfirmationPage = default(bool?), string script = default(string), string url = default(string))
        {
            Html = html;
            IsConfirmationPage = isConfirmationPage;
            Script = script;
            Url = url;
        }

        /// <summary>
        /// Gets or sets HTML form
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "html")]
        public string Html { get; set; }

        /// <summary>
        /// Gets or sets indicates whether the requested form is a
        /// confirmation page
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "isConfirmationPage")]
        public bool? IsConfirmationPage { get; set; }

        /// <summary>
        /// Gets or sets validation scripts
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "script")]
        public string Script { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

    }
}
