// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class MailingContactClickResponse
    {
        /// <summary>
        /// Initializes a new instance of the MailingContactClickResponse
        /// class.
        /// </summary>
        public MailingContactClickResponse() { }

        /// <summary>
        /// Initializes a new instance of the MailingContactClickResponse
        /// class.
        /// </summary>
        public MailingContactClickResponse(System.Collections.Generic.IList<MailingContactClick> clicks = default(System.Collections.Generic.IList<MailingContactClick>), Paging paging = default(Paging))
        {
            Clicks = clicks;
            Paging = paging;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "clicks")]
        public System.Collections.Generic.IList<MailingContactClick> Clicks { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "paging")]
        public Paging Paging { get; set; }

    }
}
