// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class MailingContactClick
    {
        /// <summary>
        /// Initializes a new instance of the MailingContactClick class.
        /// </summary>
        public MailingContactClick() { }

        /// <summary>
        /// Initializes a new instance of the MailingContactClick class.
        /// </summary>
        /// <param name="clickDate">Date & time the click occurred</param>
        public MailingContactClick(System.DateTime clickDate, int linkId)
        {
            ClickDate = clickDate;
            LinkId = linkId;
        }

        /// <summary>
        /// Gets or sets date &amp; time the click occurred
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "clickDate")]
        public System.DateTime ClickDate { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "linkId")]
        public int LinkId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
