// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class MailingContactOpenResponse
    {
        /// <summary>
        /// Initializes a new instance of the MailingContactOpenResponse class.
        /// </summary>
        public MailingContactOpenResponse() { }

        /// <summary>
        /// Initializes a new instance of the MailingContactOpenResponse class.
        /// </summary>
        public MailingContactOpenResponse(System.Collections.Generic.IList<MailingContactOpen> opens = default(System.Collections.Generic.IList<MailingContactOpen>), Paging paging = default(Paging))
        {
            Opens = opens;
            Paging = paging;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "opens")]
        public System.Collections.Generic.IList<MailingContactOpen> Opens { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "paging")]
        public Paging Paging { get; set; }

    }
}
