// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MailingStats
    {
        /// <summary>
        /// Initializes a new instance of the MailingStats class.
        /// </summary>
        public MailingStats() { }

        /// <summary>
        /// Initializes a new instance of the MailingStats class.
        /// </summary>
        public MailingStats(int acceptedCount, int clickCount, int conversionClickCount, int hardbounceCount, int notRetainedAfterBounceCount, int openCount, int openRenderedCount, int sentCount, int softbounceCount, int unsubscribeCount, long? conversionValue = default(long?), int? shoppingcartConvertedCount = default(int?), int? shoppingcartCreatedCount = default(int?), int? toWebshopCount = default(int?))
        {
            AcceptedCount = acceptedCount;
            ClickCount = clickCount;
            ConversionClickCount = conversionClickCount;
            ConversionValue = conversionValue;
            HardbounceCount = hardbounceCount;
            NotRetainedAfterBounceCount = notRetainedAfterBounceCount;
            OpenCount = openCount;
            OpenRenderedCount = openRenderedCount;
            SentCount = sentCount;
            ShoppingcartConvertedCount = shoppingcartConvertedCount;
            ShoppingcartCreatedCount = shoppingcartCreatedCount;
            SoftbounceCount = softbounceCount;
            ToWebshopCount = toWebshopCount;
            UnsubscribeCount = unsubscribeCount;
        }

        /// <summary>
        /// Accepted = Sent - hard bounce - soft bounce
        /// </summary>
        [JsonProperty(PropertyName = "acceptedCount")]
        public int AcceptedCount { get; set; }

        /// <summary>
        /// Unique clicks
        /// </summary>
        [JsonProperty(PropertyName = "clickCount")]
        public int ClickCount { get; set; }

        /// <summary>
        /// Unique clicks on links marked as 'conversion'
        /// </summary>
        [JsonProperty(PropertyName = "conversionClickCount")]
        public int ConversionClickCount { get; set; }

        /// <summary>
        /// Total conversion value in cents (eCom only)
        /// </summary>
        [JsonProperty(PropertyName = "conversionValue")]
        public long? ConversionValue { get; set; }

        /// <summary>
        /// Number of hard bounces
        /// </summary>
        [JsonProperty(PropertyName = "hardbounceCount")]
        public int HardbounceCount { get; set; }

        /// <summary>
        /// Hard bounces + 4x soft bounced in a row
        /// </summary>
        [JsonProperty(PropertyName = "notRetainedAfterBounceCount")]
        public int NotRetainedAfterBounceCount { get; set; }

        /// <summary>
        /// Unique opens
        /// </summary>
        [JsonProperty(PropertyName = "openCount")]
        public int OpenCount { get; set; }

        /// <summary>
        /// Unique rendered opens (images downloaded)
        /// </summary>
        [JsonProperty(PropertyName = "openRenderedCount")]
        public int OpenRenderedCount { get; set; }

        /// <summary>
        /// Number of recipients
        /// </summary>
        [JsonProperty(PropertyName = "sentCount")]
        public int SentCount { get; set; }

        /// <summary>
        /// Unique converted shopping carts (eCom only)
        /// </summary>
        [JsonProperty(PropertyName = "shoppingcartConvertedCount")]
        public int? ShoppingcartConvertedCount { get; set; }

        /// <summary>
        /// Unique created shopping carts (eCom only)
        /// </summary>
        [JsonProperty(PropertyName = "shoppingcartCreatedCount")]
        public int? ShoppingcartCreatedCount { get; set; }

        /// <summary>
        /// Number of soft bounces
        /// </summary>
        [JsonProperty(PropertyName = "softbounceCount")]
        public int SoftbounceCount { get; set; }

        /// <summary>
        /// Unique clicks to webshop (eCom only)
        /// </summary>
        [JsonProperty(PropertyName = "toWebshopCount")]
        public int? ToWebshopCount { get; set; }

        /// <summary>
        /// Number of unsubscribed contacts
        /// </summary>
        [JsonProperty(PropertyName = "unsubscribeCount")]
        public int UnsubscribeCount { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
