// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class MailingContactOpen
    {
        /// <summary>
        /// Initializes a new instance of the MailingContactOpen class.
        /// </summary>
        public MailingContactOpen() { }

        /// <summary>
        /// Initializes a new instance of the MailingContactOpen class.
        /// </summary>
        /// <param name="openDate">Date & time the open occurred</param>
        public MailingContactOpen(System.DateTime openDate)
        {
            OpenDate = openDate;
        }

        /// <summary>
        /// Gets or sets date &amp; time the open occurred
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "openDate")]
        public System.DateTime OpenDate { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
