// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MailingClick
    {
        /// <summary>
        /// Initializes a new instance of the MailingClick class.
        /// </summary>
        public MailingClick() { }

        /// <summary>
        /// Initializes a new instance of the MailingClick class.
        /// </summary>
        public MailingClick(DateTime clickDate, ContactIdentifier contactIdentifier, int linkId)
        {
            ClickDate = clickDate;
            ContactIdentifier = contactIdentifier;
            LinkId = linkId;
        }

        /// <summary>
        /// Date &amp; time the click occurred
        /// </summary>
        [JsonProperty(PropertyName = "clickDate")]
        public DateTime ClickDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contactIdentifier")]
        public ContactIdentifier ContactIdentifier { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "linkId")]
        public int LinkId { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (ContactIdentifier == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ContactIdentifier");
            }
            if (this.ContactIdentifier != null)
            {
                this.ContactIdentifier.Validate();
            }
        }
    }
}
