// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MailingContactClick
    {
        /// <summary>
        /// Initializes a new instance of the MailingContactClick class.
        /// </summary>
        public MailingContactClick() { }

        /// <summary>
        /// Initializes a new instance of the MailingContactClick class.
        /// </summary>
        public MailingContactClick(DateTime clickDate, int linkId)
        {
            ClickDate = clickDate;
            LinkId = linkId;
        }

        /// <summary>
        /// Date &amp; time the click occurred
        /// </summary>
        [JsonProperty(PropertyName = "clickDate")]
        public DateTime ClickDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "linkId")]
        public int LinkId { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
