// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MailingOpenResponse
    {
        /// <summary>
        /// Initializes a new instance of the MailingOpenResponse class.
        /// </summary>
        public MailingOpenResponse() { }

        /// <summary>
        /// Initializes a new instance of the MailingOpenResponse class.
        /// </summary>
        public MailingOpenResponse(IList<MailingOpen> opens = default(IList<MailingOpen>), Paging paging = default(Paging))
        {
            Opens = opens;
            Paging = paging;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "opens")]
        public IList<MailingOpen> Opens { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paging")]
        public Paging Paging { get; set; }

    }
}
