// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MailingContactOpen
    {
        /// <summary>
        /// Initializes a new instance of the MailingContactOpen class.
        /// </summary>
        public MailingContactOpen() { }

        /// <summary>
        /// Initializes a new instance of the MailingContactOpen class.
        /// </summary>
        public MailingContactOpen(DateTime openDate)
        {
            OpenDate = openDate;
        }

        /// <summary>
        /// Date &amp; time the open occurred
        /// </summary>
        [JsonProperty(PropertyName = "openDate")]
        public DateTime OpenDate { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
