// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MailingRecipientResponse
    {
        /// <summary>
        /// Initializes a new instance of the MailingRecipientResponse class.
        /// </summary>
        public MailingRecipientResponse() { }

        /// <summary>
        /// Initializes a new instance of the MailingRecipientResponse class.
        /// </summary>
        public MailingRecipientResponse(Paging paging = default(Paging), IList<MailingRecipient> recipients = default(IList<MailingRecipient>))
        {
            Paging = paging;
            Recipients = recipients;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paging")]
        public Paging Paging { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recipients")]
        public IList<MailingRecipient> Recipients { get; set; }

    }
}
