// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class Mailing
    {
        /// <summary>
        /// Initializes a new instance of the Mailing class.
        /// </summary>
        public Mailing() { }

        /// <summary>
        /// Initializes a new instance of the Mailing class.
        /// </summary>
        /// <param name="encryptedId">encryptedMailingId (Use '/mailing/*' to
        /// request additional data)</param>
        /// <param name="name">Mailing name</param>
        /// <param name="scheduledStartDate">Date & time the mailing was
        /// scheduled to send</param>
        /// <param name="sentCount">Number of mailings sent</param>
        /// <param name="type">Possible values include: 'EMAIL', 'SMS',
        /// 'DM'</param>
        /// <param name="archiveLink">Link to an online version of the
        /// mailing</param>
        public Mailing(string encryptedId, string name, System.DateTime scheduledStartDate, int sentCount, string type, string archiveLink = default(string))
        {
            ArchiveLink = archiveLink;
            EncryptedId = encryptedId;
            Name = name;
            ScheduledStartDate = scheduledStartDate;
            SentCount = sentCount;
            Type = type;
        }

        /// <summary>
        /// Gets or sets link to an online version of the mailing
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "archiveLink")]
        public string ArchiveLink { get; set; }

        /// <summary>
        /// Gets or sets encryptedMailingId (Use '/mailing/*' to request
        /// additional data)
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "encryptedId")]
        public string EncryptedId { get; set; }

        /// <summary>
        /// Gets or sets mailing name
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets date &amp; time the mailing was scheduled to send
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "scheduledStartDate")]
        public System.DateTime ScheduledStartDate { get; set; }

        /// <summary>
        /// Gets or sets number of mailings sent
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "sentCount")]
        public int SentCount { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'EMAIL', 'SMS', 'DM'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (EncryptedId == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "EncryptedId");
            }
            if (Name == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Name");
            }
            if (Type == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Type");
            }
        }
    }
}
