// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class OrderRequest
    {
        /// <summary>
        /// Initializes a new instance of the OrderRequest class.
        /// </summary>
        public OrderRequest() { }

        /// <summary>
        /// Initializes a new instance of the OrderRequest class.
        /// </summary>
        public OrderRequest(Order order, bool? update = default(bool?))
        {
            Order = order;
            Update = update;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "order")]
        public Order Order { get; set; }

        /// <summary>
        /// Only existing orders can be updated - Default value: false
        /// </summary>
        [JsonProperty(PropertyName = "update")]
        public bool? Update { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Order == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Order");
            }
            if (this.Order != null)
            {
                this.Order.Validate();
            }
        }
    }
}
