// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class OrderRequest
    {
        /// <summary>
        /// Initializes a new instance of the OrderRequest class.
        /// </summary>
        public OrderRequest() { }

        /// <summary>
        /// Initializes a new instance of the OrderRequest class.
        /// </summary>
        /// <param name="update">Only existing orders can be updated - Default
        /// value: false</param>
        public OrderRequest(Order order, bool? update = default(bool?))
        {
            Order = order;
            Update = update;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "order")]
        public Order Order { get; set; }

        /// <summary>
        /// Gets or sets only existing orders can be updated - Default value:
        /// false
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "update")]
        public bool? Update { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Order == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Order");
            }
            if (this.Order != null)
            {
                this.Order.Validate();
            }
        }
    }
}
