// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Paging
    {
        /// <summary>
        /// Initializes a new instance of the Paging class.
        /// </summary>
        public Paging() { }

        /// <summary>
        /// Initializes a new instance of the Paging class.
        /// </summary>
        public Paging(int? after = default(int?), string next = default(string))
        {
            After = after;
            Next = next;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "after")]
        public int? After { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "next")]
        public string Next { get; set; }

    }
}
