// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class ParamsModel
    {
        /// <summary>
        /// Initializes a new instance of the ParamsModel class.
        /// </summary>
        public ParamsModel() { }

        /// <summary>
        /// Initializes a new instance of the ParamsModel class.
        /// </summary>
        /// <param name="outputFormat">default: HTML4STRICT. Possible values
        /// include: 'HTML4STRICT', 'XHTML1STRICT'</param>
        /// <param name="outputMode">default: TABLES. Possible values include:
        /// 'TABLES', 'DIV'</param>
        public ParamsModel(System.Collections.Generic.IDictionary<string, System.Collections.Generic.IList<string>> formParams, string postUrl, string outputFormat = default(string), string outputMode = default(string))
        {
            FormParams = formParams;
            OutputFormat = outputFormat;
            OutputMode = outputMode;
            PostUrl = postUrl;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "formParams")]
        public System.Collections.Generic.IDictionary<string, System.Collections.Generic.IList<string>> FormParams { get; set; }

        /// <summary>
        /// Gets or sets default: HTML4STRICT. Possible values include:
        /// 'HTML4STRICT', 'XHTML1STRICT'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "outputFormat")]
        public string OutputFormat { get; set; }

        /// <summary>
        /// Gets or sets default: TABLES. Possible values include: 'TABLES',
        /// 'DIV'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "outputMode")]
        public string OutputMode { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "postUrl")]
        public string PostUrl { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (FormParams == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "FormParams");
            }
            if (PostUrl == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "PostUrl");
            }
        }
    }
}
