// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class Product
    {
        /// <summary>
        /// Initializes a new instance of the Product class.
        /// </summary>
        public Product() { }

        /// <summary>
        /// Initializes a new instance of the Product class.
        /// </summary>
        /// <param name="externalId">externalProductId - Specified product
        /// reference by external system</param>
        /// <param name="link">Link to the product page</param>
        /// <param name="name">Product name</param>
        /// <param name="brand">Product brand</param>
        /// <param name="category">Product category</param>
        /// <param name="changeDate">Date & time the product has been changed
        /// - Cannot be modified</param>
        /// <param name="creationDate">Date & time the product was created  -
        /// Cannot be modified</param>
        /// <param name="deleted">Indicates whether a product is deleted -
        /// Default value: false</param>
        /// <param name="description">Product description</param>
        /// <param name="oldPrice">Only used for discounted products</param>
        /// <param name="reviewLink">Link to the review page</param>
        /// <param name="stock">Default value: UNKNOWN. Possible values
        /// include: 'LIMITED', 'GOOD', 'UNKNOWN'</param>
        /// <param name="visible">Defines whether the product is visible in
        /// MailPlus - Default value: true</param>
        public Product(string externalId, string imageUrl, string link, string name, string price, string addToCartLink = default(string), string brand = default(string), string category = default(string), System.DateTime? changeDate = default(System.DateTime?), System.DateTime? creationDate = default(System.DateTime?), bool? deleted = default(bool?), string description = default(string), string gtin = default(string), string imageLargeUrl = default(string), string language = default(string), string oldPrice = default(string), string ratingImageUrl = default(string), string ratingValue = default(string), string reviewLink = default(string), string sku = default(string), System.Collections.Generic.IList<ProductSpecification> specifications = default(System.Collections.Generic.IList<ProductSpecification>), string stock = default(string), bool? visible = default(bool?))
        {
            AddToCartLink = addToCartLink;
            Brand = brand;
            Category = category;
            ChangeDate = changeDate;
            CreationDate = creationDate;
            Deleted = deleted;
            Description = description;
            ExternalId = externalId;
            Gtin = gtin;
            ImageLargeUrl = imageLargeUrl;
            ImageUrl = imageUrl;
            Language = language;
            Link = link;
            Name = name;
            OldPrice = oldPrice;
            Price = price;
            RatingImageUrl = ratingImageUrl;
            RatingValue = ratingValue;
            ReviewLink = reviewLink;
            Sku = sku;
            Specifications = specifications;
            Stock = stock;
            Visible = visible;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "addToCartLink")]
        public string AddToCartLink { get; set; }

        /// <summary>
        /// Gets or sets product brand
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "brand")]
        public string Brand { get; set; }

        /// <summary>
        /// Gets or sets product category
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "category")]
        public string Category { get; set; }

        /// <summary>
        /// Gets or sets date &amp; time the product has been changed - Cannot
        /// be modified
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "changeDate")]
        public System.DateTime? ChangeDate { get; set; }

        /// <summary>
        /// Gets or sets date &amp; time the product was created  - Cannot be
        /// modified
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "creationDate")]
        public System.DateTime? CreationDate { get; set; }

        /// <summary>
        /// Gets or sets indicates whether a product is deleted - Default
        /// value: false
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "deleted")]
        public bool? Deleted { get; set; }

        /// <summary>
        /// Gets or sets product description
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets externalProductId - Specified product reference by
        /// external system
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "externalId")]
        public string ExternalId { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "gtin")]
        public string Gtin { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "imageLargeUrl")]
        public string ImageLargeUrl { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "imageUrl")]
        public string ImageUrl { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "language")]
        public string Language { get; set; }

        /// <summary>
        /// Gets or sets link to the product page
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "link")]
        public string Link { get; set; }

        /// <summary>
        /// Gets or sets product name
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets only used for discounted products
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "oldPrice")]
        public string OldPrice { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "price")]
        public string Price { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ratingImageUrl")]
        public string RatingImageUrl { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ratingValue")]
        public string RatingValue { get; set; }

        /// <summary>
        /// Gets or sets link to the review page
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "reviewLink")]
        public string ReviewLink { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "sku")]
        public string Sku { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "specifications")]
        public System.Collections.Generic.IList<ProductSpecification> Specifications { get; set; }

        /// <summary>
        /// Gets or sets default value: UNKNOWN. Possible values include:
        /// 'LIMITED', 'GOOD', 'UNKNOWN'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "stock")]
        public string Stock { get; set; }

        /// <summary>
        /// Gets or sets defines whether the product is visible in MailPlus -
        /// Default value: true
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "visible")]
        public bool? Visible { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ExternalId == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "ExternalId");
            }
            if (ImageUrl == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "ImageUrl");
            }
            if (Link == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Link");
            }
            if (Name == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Name");
            }
            if (Price == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Price");
            }
            if (this.Specifications != null)
            {
                foreach (var element in this.Specifications)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
