// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Property
    {
        /// <summary>
        /// Initializes a new instance of the Property class.
        /// </summary>
        public Property() { }

        /// <summary>
        /// Initializes a new instance of the Property class.
        /// </summary>
        public Property(string description, string name, string type, IList<SetPropertyEntry> entries = default(IList<SetPropertyEntry>))
        {
            Description = description;
            Entries = entries;
            Name = name;
            Type = type;
        }

        /// <summary>
        /// Description label of the property
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Only visible for 'SET' type. Defines the options and corresponding
        /// bit values
        /// </summary>
        [JsonProperty(PropertyName = "entries")]
        public IList<SetPropertyEntry> Entries { get; set; }

        /// <summary>
        /// Name of the property
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Possible values include: 'birthdate', 'date', 'dateTime', 'email',
        /// 'gender', 'int', 'mobNr', 'money', 'postcode', 'set', 'string'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Description == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Description");
            }
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (Type == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Type");
            }
            if (this.Entries != null)
            {
                foreach (var element in this.Entries)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
