// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class SetPropertyFlag
    {
        /// <summary>
        /// Initializes a new instance of the SetPropertyFlag class.
        /// </summary>
        public SetPropertyFlag() { }

        /// <summary>
        /// Initializes a new instance of the SetPropertyFlag class.
        /// </summary>
        public SetPropertyFlag(long bit, bool enabled)
        {
            Bit = bit;
            Enabled = enabled;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "bit")]
        public long Bit { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "enabled")]
        public bool Enabled { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
