// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SetPropertyFlag
    {
        /// <summary>
        /// Initializes a new instance of the SetPropertyFlag class.
        /// </summary>
        public SetPropertyFlag() { }

        /// <summary>
        /// Initializes a new instance of the SetPropertyFlag class.
        /// </summary>
        public SetPropertyFlag(long bit, bool enabled)
        {
            Bit = bit;
            Enabled = enabled;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bit")]
        public long Bit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "enabled")]
        public bool Enabled { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
