// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class SetPropertyEntry
    {
        /// <summary>
        /// Initializes a new instance of the SetPropertyEntry class.
        /// </summary>
        public SetPropertyEntry() { }

        /// <summary>
        /// Initializes a new instance of the SetPropertyEntry class.
        /// </summary>
        /// <param name="description">Description of an option</param>
        public SetPropertyEntry(long bit, string description, int rank)
        {
            Bit = bit;
            Description = description;
            Rank = rank;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "bit")]
        public long Bit { get; set; }

        /// <summary>
        /// Gets or sets description of an option
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "rank")]
        public int Rank { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Description == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Description");
            }
        }
    }
}
