// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SetPropertyEntry
    {
        /// <summary>
        /// Initializes a new instance of the SetPropertyEntry class.
        /// </summary>
        public SetPropertyEntry() { }

        /// <summary>
        /// Initializes a new instance of the SetPropertyEntry class.
        /// </summary>
        public SetPropertyEntry(long bit, string description, int rank)
        {
            Bit = bit;
            Description = description;
            Rank = rank;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bit")]
        public long Bit { get; set; }

        /// <summary>
        /// Description of an option
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rank")]
        public int Rank { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Description == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Description");
            }
        }
    }
}
