// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MailPlus.Models
{
    using System.Linq;

    public partial class TemporaryList
    {
        /// <summary>
        /// Initializes a new instance of the TemporaryList class.
        /// </summary>
        public TemporaryList() { }

        /// <summary>
        /// Initializes a new instance of the TemporaryList class.
        /// </summary>
        /// <param name="createdAt">Date & time the temporary list was
        /// created</param>
        /// <param name="name">Temporary list name visible in MailPlus</param>
        /// <param name="type">Default value: API - Cannot be modified.
        /// Possible values include: 'IMPORT', 'RESPONSE', 'API',
        /// 'SPLIT'</param>
        /// <param name="externalTemporaryListId">Specified list reference by
        /// external system</param>
        public TemporaryList(System.DateTime createdAt, string name, string type, string externalTemporaryListId = default(string))
        {
            CreatedAt = createdAt;
            ExternalTemporaryListId = externalTemporaryListId;
            Name = name;
            Type = type;
        }

        /// <summary>
        /// Gets or sets date &amp; time the temporary list was created
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "createdAt")]
        public System.DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets specified list reference by external system
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "externalTemporaryListId")]
        public string ExternalTemporaryListId { get; set; }

        /// <summary>
        /// Gets or sets temporary list name visible in MailPlus
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets default value: API - Cannot be modified. Possible
        /// values include: 'IMPORT', 'RESPONSE', 'API', 'SPLIT'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Name");
            }
            if (Type == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Type");
            }
        }
    }
}
